# Generated by Django 4.2.2 on 2023-06-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_user_location_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
