# Generated by Django 4.2.2 on 2023-06-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_car_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
