# Generated by Django 4.2.2 on 2023-07-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_car_cylinders_alter_car_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturing_year',
            field=models.PositiveIntegerField(),
        ),
    ]
