# Generated by Django 4.2.2 on 2023-07-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_car_manufacturing_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.carbrand')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_models',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.carmodels'),
        ),
    ]
