# Generated by Django 4.2.2 on 2023-07-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_carbrand_carmodels_car_car_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(default='2.0-liter engine', max_length=50),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='cars_images'),
        ),
    ]
