# Generated by Django 4.2.2 on 2023-07-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_car_engine_capacity_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='damage',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
