# Generated by Django 4.2.2 on 2023-07-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_car_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='technicalcondition',
            name='status',
            field=models.CharField(choices=[('Y', 'Very Good'), ('x', 'Good'), ('N', 'Bad'), ('UK', 'UnKnown')], max_length=50),
        ),
    ]
