# Generated by Django 4.2.2 on 2023-07-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_car_price_alter_technicalcondition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_kind',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Company'), ('A', 'Admin')], default='User', max_length=50),
        ),
    ]
