# Generated by Django 4.2.2 on 2023-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_user_user_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drive_type',
            field=models.CharField(choices=[('4WD', '4WD'), ('AWD', 'AWD'), ('FWD', 'FWD'), ('RWD', 'RWD')], default='4WD', max_length=50),
        ),
    ]
