# Generated by Django 4.2.2 on 2023-07-22 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_car_drive_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_kind',
            field=models.CharField(choices=[('User', 'User'), ('Company', 'Company'), ('Admin', 'Admin')], default='User', max_length=50),
        ),
        migrations.CreateModel(
            name='RequestAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.car')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
