# Generated by Django 4.2.2 on 2023-07-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_user_user_kind_requestauction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Easytronic', 'Easytronic')], max_length=150),
        ),
    ]
