# Generated by Django 4.2.2 on 2023-08-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_alter_requestauction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=500),
        ),
    ]
